```{r cargar curva cero cupón}
curva <- read.csv("../data/Curva_0C.csv", sep = ";", col.names = c("vencimiento", "colones", "dolares"), dec = ",")
```
```{r}
library(dplyr)
```


```{r, calcular precio forward}
forward <- function(t, S, T, moneda){
  if(t == 0){ #versión normal
    idS <- which.min(abs(curva$vencimiento - S))
    idT <- which.min(abs(curva$vencimiento - T))
    rhoS <- curva[[moneda]][idS]/100
    rhoT <- curva[[moneda]][idT]/100
    PS <- ((1+rhoS)^-S)
    PT <- ((1+rhoT)^-T)
    return(PT/PS)
  }
}
```

```{r}
forward(0, 0, 0.09, 'colones')
```
# Tasas r_t
```{r}
set.seed(123) 
# Función para generar árbol de tasas de interés
# Recibe u(2), d(2), número de iteraciones
ho_lee <- function(u_2, d_2, n, moneda, bern){
  k <- d_2/u_2
  q <- (1-d_2)/(u_2 - d_2)
  r_0 <- -log(forward(0, 0, 1/12, moneda))
  U <- 0
  S <- 0
  # Seguir un camino
  resultados <- data.frame(periodo = 1:(n+1),
                           r_t  = rep(NA_real_, n+1),
                           U_t  = rep(NA_real_, n+1),
                           d = rep(NA_real_, n + 1))
  resultados$r_t[1] <- r_0
  resultados$U_t[1] <- 0
  # Excluimos el caso para d(2)
  S <- S + 1/12 #incrementos mensuales
  if(bern[1] == 1){
    U <- U + 1
  }
  resultados$U_t[1+1] <- U
  d <- d_2
  resultados$d[2] <- d
  r_t <- -log(forward(0, S, S+1/12, moneda)) - log(d) + U*log(k)
  resultados$r_t[1+1] <- r_t
  for(i in 2:n){
    S <- S + 1/12 #incrementos mensuales
    if(bern[i] == 1){
      U <- U + 1
    }
    resultados$U_t[i+1] <- U
    d <- k^(i-1)/((1-q)*k^(i-1) + q)
    resultados$d[i+1] <- d
    r_t <- -log(forward(0, S, S+1/12, moneda)) - log(d) + U*log(k)
    resultados$r_t[i+1] <- r_t
  }
  return(resultados)
}
```
## Prueba ejecución
```{r}
u_2 <- 1.0001
d_2 <- 0.9999
ho_lee(u_2, d_2, 12, 'colones')
-log(forward(0, 0, 1/12, 'colones'))
```

## Árbol de precios
```{r}
# omegas <- rbinom(n = 12, size = 1, prob = (1-d_2)/(u_2 - d_2))
# precios <- function(u_2, d_2, n, moneda, omegas){
#   k <- d_2/u_2
#   q <- (1-d_2)/(u_2 - d_2)
#   U_t <- c(0, omegas)
#   resultados <- data.frame(periodo = 1:(n+1),
#                            precio  = rep(NA_real_, n+1),
#                            U_t  = U_t)
#   resultados$precio[1] <- curva[[moneda]][n/12] # se esperan periodos, vencimiento en un año, número entero
#   i <- 1
#   while(n - i + 1 > 2){
#     if(omegas[i] == 1){
#       u <- 1/((1-q)*k^(n - i + 1) + q) #calcula u(n)
#       resultados$precio[i + 1] <- u*forward(i-1, i, n, moneda) 
#     }
#     else{
#       d <- k^(i-1)/((1-q)*k^(i-1) + q)
#       resultados$precio[i + 1] <- d*forward(i-1, i, n, moneda)
#     }
#     i <- i+1
#   }
#   # Separamos el caso u(2) y d(2)
#   if(omegas[i] == 1){
#     resultados$precio[i] <- u_2*forward(i-1, i, n, moneda)
#   }
#   else{
#     resultados$precio[i] <- d_2*forward(i-1, i, n, moneda)
#   }
# }
```

```{r}
# precios(u_2, d_2, 12, 'colones', omegas)
```
```{r}
precios_arriba <- function(u_2, d_2, n, moneda){
  k <- d_2/u_2
  q <- (1-d_2)/(u_2 - d_2)
  resultados <- data.frame(periodo = 0:n,
                           precio  = rep(NA_real_, n+1),
                           U_t  = 0:n)
  # Se construye la rama de arriba
  u <- function(t){
    u <- 1/((1-q)*k^(t) + q)
  }
  # Separamos las primeras tres
  resultados$precio[1] <- forward(0, 0, n/12, moneda) #Precio actual
  resultados$precio[2] <- u(n)*forward(0, 1/12, n/12, moneda) #Primer salto
  resultados$precio[3] <- u(n - 1)*resultados$precio[2]/(u_2*forward(0, 1/12, 2/12, moneda)) #Segundo salto
  i <- 3
  while(n - i > 1){
    t <- i/12
    resultados$precio[i + 1] <- u(n - i + 1)*resultados$precio[i]/(u(i)*forward(0, t - 1/12, t, moneda))
    i <- i + 1
  }
  resultados$precio[n] <- u_2*resultados$precio[n - 1]/(u(n - 1)*forward(0, n - 2/12, n - 1/12, moneda))
  resultados$precio[n + 1] <- 1
  return(resultados)
}
```

```{r}
precios_arriba(u_2, d_2, 12, 'colones')
```

```{r}
otros_precios <- function(u_2, d_2, n, moneda, omegas){
  sup <- precios_arriba(u_2, d_2, n, moneda)
  k <- d_2/u_2
  q <- (1-d_2)/(u_2 - d_2)
  resultados <- data.frame(periodo = 1:(n+1),
                           precio  = sup$precio, #primero y último son iguales
                           U_t  = rep(NA_real_, n+1))
  resultados$U_t[1] <- 0
  for(i in 2:n){
    resultados$U_t[i] <- resultados$U_t[i - 1] + omegas[i - 1]
    resultados$precio[i] <- k^((i - 1 - resultados$U_t[i])*(n - i + 1))*sup$precio[i] #Multiplicar factor la cantidad de veces necesaria
  }
  return(resultados)
}
```

```{r}
omegas <- rbinom(n = 12, size = 1, prob = (1-d_2)/(u_2 - d_2))
otros_precios(u_2, d_2, 12, 'colones', omegas)
omegas
precios_arriba(u_2, d_2, 12, 'colones')
```


# Árbol conjunto
```{r}
conjunto <- function(u_2, d_2, n, moneda, omegas, uS, dS, accion){
  res <- ho_lee(u_2, d_2, n, moneda, omegas)
  r <- res$r_t
  print(r)
  k <- d_2/u_2
  q <- (1-d_2)/(u_2 - d_2)
  resultados <- data.frame(periodo = 1:(n+1),
                           S  = rep(NA_real_, n+1),
                           proba_S = rep(NA_real_, n+1),
                           U_t  = res$U_t)
  resultados$S[1] <- accion
  # Separamos la primera iteración
  q_i <- ifelse(exp(r[1]) > uS, (exp(log(uS)) - dS)/(uS - dS), ifelse(exp(r[1]) < dS, (exp(log(dS)) - dS)/(uS - dS), (exp(r[1]) - dS)/(uS - dS)))
  bern <- rbinom(n = 1, size = 1, prob = q_i)
  if(bern == 1){
    resultados$S[2] <- resultados$S[1]*uS
    resultados$proba_S[2] <- q_i
  }
  else{
    resultados$S[2] <- resultados$S[1]*dS
    resultados$proba_S[2] <- 1 - q_i
  }
  for (i in 2:n){
    q_i <- ifelse(exp(r[i]) > uS, (exp(log(uS)) - dS)/(uS - dS), ifelse(exp(r[i]) < dS, (exp(log(dS)) - dS)/(uS - dS), (exp(r[i]) - dS)/(uS - dS)))
    bern <- rbinom(n = 1, size = 1, prob = q_i)
    if(bern == 1){
      resultados$S[i + 1] <- resultados$S[i]*uS
      if(omegas[i - 1] == 1){
        resultados$proba_S[i + 1] <- resultados$proba_S[i]*q_i*q
      }
      else{
        resultados$proba_S[i + 1] <- resultados$proba_S[i]*q_i*(1 - q)
      }
      
    }
    else{
      resultados$S[i + 1] <- resultados$S[i]*dS
      if(omegas[i - 1] == 1){
        resultados$proba_S[i + 1] <- resultados$proba_S[i]*(1 - q_i)*q
      }
      else{
        resultados$proba_S[i + 1] <- resultados$proba_S[i]*(1 - q_i)*(1 - q)
      }
      
    }
  }
  return(resultados)
}
```

```{r}
uS <- 1.003618
dS <- 0.9963954
conjunto(u_2, d_2, 12, 'colones', omegas, uS, dS, 200)

```





```{r}
valor_teorico_accion <- function(Ts, S0, moneda) {
  sapply(Ts, function(T) {
    if (T == 0) {
      return(S0)
    }
    P_0T <- forward(0, 0, T, moneda) 
    S0 / P_0T                         
  })
}

Ts <- c(0, 2.5, 5, 10, 15)
S0 <- 24000  # tu 'accion'
valor_teorico_accion(Ts, S0, "colones")

```
# Simulación de acciones
```{r}
uS <- 1.003618
dS <- 0.9963954

# Parámetros
n    <- 180
Ts   <- c(0, 2.5, 5, 10, 15)       # años
idx  <- Ts * 12 + 1                # índices de las filas en S
nsim <- 10

accion <- 24000                      
moneda <- "colones"               

sim_S <- matrix(NA_real_, nrow = nsim, ncol = length(Ts))
colnames(sim_S) <- paste0("t_", Ts)

for(sim in 1:nsim){
  omegas <- rbinom(n = n, size = 1, prob = (1-d_2)/(u_2 - d_2))
  camino <- conjunto(u_2, d_2, n, moneda, omegas, uS, dS, accion)
  sim_S[sim, ] <- camino$S[idx]
}

# Valor esperado numérico (promedio de las 10 simulaciones)
E_S <- colMeans(sim_S)

E_S     # valor esperado aproximado en 0, 2.5, 5, 10 y 15 años

```

